/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { NewNFT_v1 } from "./NewNFT_v1";
export type { NewNFT_v2 } from "./NewNFT_v2";
export type { NewNFT_v3 } from "./NewNFT_v3";
export type { NewNFT_v4 } from "./NewNFT_v4";
export type { NewNFT_v5 } from "./NewNFT_v5";
export type { OldNFT } from "./OldNFT";
